"""
Data models for candidate ranking system.

Defines Pydantic models for candidate profiles and ranking results.
Used throughout the system for structured data validation and LLM output.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class CandidateProfile(BaseModel):
    """
    Structured representation of a candidate's professional profile.

    Extracted from raw resume text by LLM-based extraction pipeline.
    Used as input for ranking against job descriptions.
    """

    skills: list[str] = Field(
        default_factory=list,
        description="Technical and professional skills (e.g., Python, AWS, Kubernetes)",
        min_length=0,
    )
    years_of_experience: float = Field(
        default=0.0,
        description="Total years of professional work experience",
        ge=0.0,
    )
    past_titles: list[str] = Field(
        default_factory=list,
        description="Job titles in reverse chronological order (most recent first)",
        min_length=0,
    )
    raw_resume_text: str | None = Field(
        default=None,
        description="Original resume text (optional, not used by LLM)",
    )

    model_config = {"frozen": False, "extra": "forbid"}


class RankingResult(BaseModel):
    """
    Result of comparing a candidate profile to a job description.

    Contains fit score (0-100) and detailed reasoning for the assessment.
    Generated by LLM-based ranking pipeline.
    """

    fit_score: int = Field(
        description="Candidate-job fit score from 0 (poor) to 100 (excellent)",
        ge=0,
        le=100,
    )
    reasoning: str = Field(
        description="Detailed explanation of score, citing specific matches and gaps",
        min_length=1,
    )

    model_config = {"frozen": False, "extra": "forbid"}
